### PR TITLE
Fixes #https://github.com/differentreality/supplies_tracker/issues/72

### LINKED ISSUE #72: Use environment variables in the settings file
You absolutely need to change your secret key ([some reasons why](https://security.stackexchange.com/a/61911)) and then switch it with something similar to:

```python
SECRET_KEY = os.environ.get('SECRET_KEY')
```

Do the same for your google API key.

### PR DESCRIPTION
**Pull request by robertpro**
Fixes #72

### CODE REVIEW

**Comment by joshcrim** [comment]
Although this is a correct way to do it in production, it will require an extra project setup step that we would ideally want to avoid in dev (setting the secret key env variable). The next issue/PR I'll be submitting is to create separate settings files for dev and prod. Once that's done we can set the prod settings file as per this PR and just throw a random string into the dev settings for the secret key because in dev it doesnt matter.

**Comment by angeanto** [comment]
@robertpro There is a conflict here , obviously we should keep ALLOWED_HOSTS = ['localhost', 'suppliestracker.pythonanywhere.com'] . Can you resolve this for testing in order to merge ?

**Comment by angeanto** [comment]
@robertpro  why i get this error ? 

screenshot from 2018-02-16 11-15-32

**Comment by robertpro** [comment]
@angeanto I am sorry, I made a mistake, but it is fixed now.

**Comment by angeanto** [comment]
you should rebase your commits in order to merge this. It works now, but i cant rebase and merge due to conflicts

**Comment by differentreality** [comment]
Thank you @robertpro for the fix!

Please use git rebase origin/master to rebase your branch and fix the conflicts, then push it again.

**Comment by robertpro** [comment]
looks like fixed: 

```
git rebase origin/master 
Current branch use_environment_variables_in_the_settings_file is up to date.
```
Sorry for the inconvenience, this is my first time helping other developers

**Comment by angeanto** [comment]
@robertpro  there's always first time. It works i merge this.Thank you

**Pull request merged**
