### PR TITLE
create config folder. modify manage.py to point to config folder for …

### PR DESCRIPTION
**Pull request by joshcrim**
create config folder. modify manage.py to point to config folder for settings. Move wsgi and settings file to config. Create master url conf, move admin urls to master url conf, include supplies_tracker urls. remove unused imports, clean up code style.

A separate config folder is recommended by [https://www.twoscoopspress.com/](url) and [https://github.com/pydanny/cookiecutter-django](url) (same author) to separate app files from project files. It will become more useful when new apps are added to the project.

### CODE REVIEW

**Comment by angeanto** [comment]
Hi @joshcrim , 

Is everything running without errors to you ? Coz , i am getting some errors including ModuleNotFoundError: No module named 'supplies_tracker.settings' . I am trying to figure this out

**Comment by joshcrim** [comment]
Are you getting the error in dev or on production? If on production, is manage.py added to git ignore?

manage.py only does 2 things (with the default setup): 1. find the settings file and 2. execute the command passed from the command line.

I updated manage.py to point to the new settings file in dev. If you're having the problem in production, check manage.py to make sure the line that loads the settings file looks like this:

`os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")`

**Comment by joshcrim** [comment]
Also, I checked out the conflicts:

In urls.py keep the HEAD for my branch, not master. My branch removes unused imports and moves the staticfiles to config/urls.py

Looks like the settings.py conflicts are just from the PEP 8 changes

**Comment by joshcrim** [comment]
Crap I didnt mean to close this, I was making changes to my git setup -_- ill re-open

**Comment by angeanto** [comment]
I am getting the error in dev. This is the ss of the errors 
i am using Pycharm Professional and when i run the whole project i get following errors. 

screenshot from 2018-02-16 10-20-20

**Although , when i started server from terminal it started without any error. I** am not sure but does this line from django.core.management import execute_from_command_line in manage.py means server starts only from terminal ?

**Comment by joshcrim** [comment]
Did a little research, it looks like maybe you need to modify your django settings inside pycharm? Try settings -> languages -> django and see what the settings file path is there.

**Comment by joshcrim** [comment]
Any luck? I've been waiting for #82 to finish before resubmitting this PR so that we don't run into any merge conflicts.

**Comment by robertpro** [comment]
I am sorry for the delay, I was not sure about what should I do, I think it is done. #82

**Pull request closed without merging**
