### PR TITLE
Fix bug #85 ( UserUpdate should filter by User)

### PR DESCRIPTION
**Pull request by kmetaxas**
1. Change User Update view URL to not use <pk> since User should be only allowed to edit his own Profile.
2. Add get_object to UserUpdate view that returns the logged in user.
3. Update template to use new url (no args)

### CODE REVIEW

**Comment by angeanto** [comment]
@kmetaxas i'll merge this soon , i am trying to fix some rebase issues

**Comment by kmetaxas** [comment]
@angeanto I've merged (not rebased) with upstream (did not see your comment until now).
I believe it should merge now.

**Comment by differentreality** [comment]
It does not. You should rebase locally, and fix the conflicts. However, it seems that you created this PR out of your master branch. You should create a new branch for every new feature you work on.

Assuming the remote for this repo here is called origin, you need to do the following:

Create a new branch with your changes (let's call the branch user_update_filter):
```
git checkout master
git checkout -b user_update_filter
```

Then sync your local master with the upstream master:
```
git checkout master
git reset --hard origin/master
```
At this point please check that:
* you are in master branch
* git status is clean
* git pull origin master says 'All up to date'

Rebase your branch:
```
git checkout user_update_filter
git rebase origin/master
```

This will tell you that there are conflicts. 
`git status` will show you which files have conflicts

Please go to the files and fix the conflicts. 
Once the conflicts are fixed:
```
git add .
git rebase --continue
git push your-remote user_update_filter
```
your-remote is the name of the remote that corresponds to this repo https://github.com/kmetaxas/supplies_tracker

Open a new PR coming from the new branch we just created :-)
Feel free to reach out if you get stuck at any step.

**Comment by differentreality** [comment]
Fixed in #88

**Pull request closed without merging**
